#!/usr/bin/env python3


import sys
import json
from fitting.core import Metadata
import re
from pathlib import Path
from rich import print


def main():
    for p in Path(sys.argv[3]).rglob("metadata.json"):
        part = p.parts[int(sys.argv[1])]
        print(part)
        matches = re.search(sys.argv[2], part)
        toy = matches.group(0)
        print(toy)
        with open(p, "r") as f:
            m = Metadata.model_validate_json(f.read())
        m.fit_region.background_toy = int(toy)
        with open(p, "w") as f:
            f.write(m.model_dump_json())


if __name__ == "__main__":
    main()
