#!/usr/bin/env bash

input_dir=$1
output_dir=$2

shopt -s globstar

python3 fitting/combine/gather.py  -o $output_dir/prefs/rate_0p0.json $input_dir/**/*0p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r 
python3 fitting/combine/gather.py  -o $output_dir/prefs/rate_1p0.json $input_dir/**/*1p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py  -o $output_dir/prefs/rate_4p0.json $input_dir/**/*4p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py  -o $output_dir/prefs/rate_16p0.json $input_dir/**/*16p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py  -o $output_dir/prefs/lim_0p0.json $input_dir/**/*0p0*/higgsCombine.lim.AsymptoticLimits.mH120.root --key limit 
python3 fitting/combine/gather.py  -o $output_dir/prefs/sig_1p0.json $input_dir/**/*1p0*/higgsCombine.sig.Significance.mH120.root --key limit 
python3 fitting/combine/gather.py  -o $output_dir/prefs/sig_4p0.json $input_dir/**/*4p0*/higgsCombine.sig.Significance.mH120.root --key limit
python3 fitting/combine/gather.py  -o $output_dir/prefs/sig_16p0.json $input_dir/**/*16p0*/higgsCombine.sig.Significance.mH120.root --key limit 


python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/rate_0p0.json $input_dir/**/*0p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/rate_1p0.json $input_dir/**/*1p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/rate_4p0.json $input_dir/**/*4p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/rate_16p0.json $input_dir/**/*16p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r

python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/rate_0p0.json $input_dir/**/*0p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/rate_1p0.json $input_dir/**/*1p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/rate_4p0.json $input_dir/**/*4p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r
python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/rate_16p0.json $input_dir/**/*16p0*/higgsCombine.fit.MultiDimFit.mH120.root --key r


python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/lim_0p0.json $input_dir/**/*0p0*/higgsCombine.lim.AsymptoticLimits.mH120.root --key limit
python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/sig_1p0.json $input_dir/**/*1p0*/higgsCombine.sig.Significance.mH120.root --key limit
python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/sig_4p0.json $input_dir/**/*4p0*/higgsCombine.sig.Significance.mH120.root --key limit
python3 fitting/combine/gather.py --algo 'uncomp' -o $output_dir/uncomp/sig_16p0.json $input_dir/**/*16p0*/higgsCombine.sig.Significance.mH120.root --key limit


python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/lim_0p0.json $input_dir/**/*0p0*/higgsCombine.lim.AsymptoticLimits.mH120.root --key limit
python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/sig_1p0.json $input_dir/**/*1p0*/higgsCombine.sig.Significance.mH120.root --key limit
python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/sig_4p0.json $input_dir/**/*4p0*/higgsCombine.sig.Significance.mH120.root --key limit
python3 fitting/combine/gather.py --algo 'comp' -o $output_dir/comp/sig_16p0.json $input_dir/**/*16p0*/higgsCombine.sig.Significance.mH120.root --key limit



