#!/usr/bin/env bash

base_dir="backgrounds/backgrounds_2025_09_19/"

low=450,1710
med=795,2205
high=1290,2700

# low=500,1500
# med=1000,2000
# high=1500,2500


function printAndRun(){
    echo "$@"
    $@
}

extras="--cuda"



function makeForCoupling(){
    local background_dir=$1
    local coupling=$2
    local dataset=$3
    local year=$3
    local low_top=0.9
    local subdir=""
    rebin=2
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/low_uncomp -s $coupling \
        -i export_hists/$subdir/$year/$coupling/uncomp_0p67_m14_vs_mChiRatio.pklz4 \
        -x $low -y 0.0,$low_top  --rebin $rebin  $extras ${@:5}
    
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/med_uncomp -s $coupling \
        -i export_hists/$subdir/$year/$coupling/uncomp_0p67_m14_vs_mChiRatio.pklz4 \
        -x $med -y 0.0,$low_top  --rebin $rebin $extras ${@:5}
    
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/high_uncomp -s $coupling \
        -i export_hists/$year/$coupling/uncomp_0p67_m14_vs_mChiRatio.pklz4 \
        -x $high -y 0.0,$low_top  --rebin $rebin $extras ${@:5}

    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/low_comp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pklz4 \
        -x $low -y 0.6,1.0  --rebin $rebin $extras ${@:5}
    
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/med_comp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pklz4 \
        -x $med -y 0.6,1.0  --rebin $rebin $extras ${@:4}
    
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/high_comp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pklz4 \
        -x $high -y 0.6,1.0  --rebin $rebin $extras ${@:4}
    
    # rebin=1
    # printAndRun \
    #     python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/low_ucomp -s $coupling \
    #     -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pklz4 \
    #     -x $low -y 0.8,1.0  --rebin $rebin $extras ${@:4}
    # 
    # printAndRun \
    #     python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/med_ucomp -s $coupling \
    #     -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pklz4 \
    #     -x $med -y 0.8,1.0  --rebin $rebin $extras ${@:4}
    # 
    # printAndRun \
    #     python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/high_ucomp -s $coupling \
    #     -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pklz4 \
    #     -x $high -y 0.8,1.0  --rebin $rebin $extras ${@:4}
}

# makeForCoupling Signal312 qcd_inclusive_2018
# makeForCoupling Signal313 qcd_inclusive_2018
# makeForCoupling Control data_JetHT_2018 --only-clip


function makeForYear(){
    makeForCoupling $base_dir/$1 Signal312 qcd_inclusive_$1 $1
    makeForCoupling $base_dir/$1 Signal313 qcd_inclusive_$1
    makeForCoupling $base_dir/$1 Control data_JetHT_$1 --only-clip
    :
}

makeForYear 2016_preVFP
makeForYear 2016_postVFP
makeForYear 2017
makeForYear 2018
makeForYear 2022_preEE
makeForYear 2022_postEE
makeForYear 2023_preBPix
makeForYear 2023_postBPix
