#!/usr/bin/env bash

outdir="deletemelater/output"

rebin=1
lr=0.02

function printAndRun(){
    echo "$@"
    $@
}

printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_312_1500_1400 -n  signal_312_1500_1400 \
    -r Signal312 -b testbackground/Signal312/med_comp/background_0/background_0.pkl \
    -s export_hists/signal_312_1500_1400/Signal312/comp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr

printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_312_1500_600 -n  signal_312_1500_600 \
    -r Signal312 -b testbackground/Signal312/med_uncomp/background_0/background_0.pkl \
    -s export_hists/signal_312_1500_600/Signal312/uncomp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr



printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_312_2000_1900 -n  signal_312_2000_1900 \
    -r Signal312 -b testbackground/Signal312/high_comp/background_0/background_0.pkl \
    -s export_hists/signal_312_2000_1900/Signal312/comp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr

printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_312_2000_900 -n  signal_312_2000_900 \
    -r Signal312 -b testbackground/Signal312/high_uncomp/background_0/background_0.pkl \
    -s export_hists/signal_312_2000_900/Signal312/uncomp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr


#############################################

# rebin=3
# lr=0.05




printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_313_1500_1400 -n  signal_313_1500_1400 \
    -r Signal313 -b testbackground/Signal313/med_comp/background_0/background_0.pkl \
    -s export_hists/signal_313_1500_1400/Signal313/comp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr

printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_313_1500_600 -n  signal_313_1500_600 \
    -r Signal313 -b testbackground/Signal313/med_uncomp/background_0/background_0.pkl \
    -s export_hists/signal_313_1500_600/Signal313/uncomp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr


printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_313_2000_1900 -n  signal_313_2000_1900 \
    -r Signal313 -b testbackground/Signal313/high_comp/background_0/background_0.pkl \
    -s export_hists/signal_313_2000_1900/Signal313/comp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr

printAndRun \
python3 -m fitting.cli estimate -o $outdir/signal_313_2000_900 -n  signal_313_2000_900 \
    -r Signal313 -b testbackground/Signal313/high_uncomp/background_0/background_0.pkl \
    -s export_hists/signal_313_2000_900/Signal313/uncomp_0p67_m14_vs_mChiCompRatio.pkl  \
    --rebin $rebin -l $lr
