#!/usr/bin/env bash

background_dir="backgrounds/background_2025_06_18_rbf"

low=500,1700
med=800,2200
high=1300,2700

# low=500,1500
# med=1000,2000
# high=1500,2500


function printAndRun(){
    echo "$@"
    $@
}

extras=""



function makeForCoupling(){
    local coupling=$1
    local dataset=$2
    local low_top=0.9
    rebin=2
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/low_uncomp -s $coupling \
        -i export_hists/$dataset/$coupling/uncomp_0p67_m14_vs_mChiRatio.pkl \
        -x $low -y 0.0,$low_top --use-cuda --rebin $rebin  $extras ${@:3}

    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/med_uncomp -s $coupling \
        -i export_hists/$dataset/$coupling/uncomp_0p67_m14_vs_mChiRatio.pkl \
        -x $med -y 0.0,$low_top --use-cuda --rebin $rebin $extras ${@:3}

    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/high_uncomp -s $coupling \
        -i export_hists/$dataset/$coupling/uncomp_0p67_m14_vs_mChiRatio.pkl \
        -x $high -y 0.0,$low_top --use-cuda --rebin $rebin $extras ${@:3}

    rebin=2
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/low_comp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pkl \
        -x $low -y 0.4,1.0 --use-cuda --rebin $rebin $extras ${@:3}

    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/med_comp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pkl \
        -x $med -y 0.4,1.0 --use-cuda --rebin $rebin $extras ${@:3}

    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/high_comp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pkl \
        -x $high -y 0.4,1.0 --use-cuda --rebin $rebin $extras ${@:3}

    rebin=1
    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/low_ucomp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pkl \
        -x $low -y 0.8,1.0 --use-cuda --rebin $rebin $extras ${@:3}

    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/med_ucomp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pkl \
        -x $med -y 0.8,1.0 --use-cuda --rebin $rebin $extras ${@:3}

    printAndRun \
        python3 -m fitting.cli bkg-smooth -n $dataset -o $background_dir/$coupling/high_ucomp -s $coupling \
        -i export_hists/$dataset/$coupling/comp_0p67_m14_vs_mChiRatio.pkl \
        -x $high -y 0.8,1.0 --use-cuda --rebin $rebin $extras ${@:3}
}


makeForCoupling Signal312 qcd_inclusive_2018
makeForCoupling Signal313 qcd_inclusive_2018
makeForCoupling Control data_JetHT_2018 --only-clip

