#!/usr/bin/env bash

in_dir=$1
output_dir=$2

shopt -s globstar

python3 -m fitting.combine.plot_sig --input2 $in_dir/uncomp/sig_1p0.json -o $output_dir/sig_uncomp_over_comp_r1.png $in_dir/comp/sig_1p0.json     "${@:3}"
python3 -m fitting.combine.plot_sig --input2 $in_dir/uncomp/sig_4p0.json -o $output_dir/sig_uncomp_over_comp_r4.png $in_dir/comp/sig_4p0.json     "${@:3}"
python3 -m fitting.combine.plot_sig --input2 $in_dir/uncomp/sig_16p0.json -o $output_dir/sig_uncomp_over_comp_r16.png $in_dir/comp/sig_16p0.json   "${@:3}"

python3 -m fitting.combine.plot_rate -o $output_dir/rate_comp_r0.png $in_dir/comp/rate_0p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_comp_r1.png $in_dir/comp/rate_1p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_comp_r4.png $in_dir/comp/rate_4p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_comp_r16.png $in_dir/comp/rate_16p0.json "${@:3}"

python3 -m fitting.combine.plot_rate -o $output_dir/rate_uncomp_r0.png $in_dir/uncomp/rate_0p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_uncomp_r1.png $in_dir/uncomp/rate_1p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_uncomp_r4.png $in_dir/uncomp/rate_4p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_uncomp_r16.png $in_dir/uncomp/rate_16p0.json "${@:3}"

python3 -m fitting.combine.plot_lim -o $output_dir/lim_comp_r0.png $in_dir/comp/lim_0p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_comp_r1.png $in_dir/comp/sig_1p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_comp_r4.png $in_dir/comp/sig_4p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_comp_r16.png $in_dir/comp/sig_16p0.json "${@:3}"

python3 -m fitting.combine.plot_lim -o $output_dir/lim_uncomp_r0.png $in_dir/uncomp/lim_0p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_uncomp_r1.png $in_dir/uncomp/sig_1p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_uncomp_r4.png $in_dir/uncomp/sig_4p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_uncomp_r16.png $in_dir/uncomp/sig_16p0.json "${@:3}"


python3 -m fitting.combine.plot_rate -o $output_dir/rate_prefs_r0.png $in_dir/prefs/rate_0p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_prefs_r1.png $in_dir/prefs/rate_1p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_prefs_r4.png $in_dir/prefs/rate_4p0.json "${@:3}"
python3 -m fitting.combine.plot_rate -o $output_dir/rate_prefs_r16.png $in_dir/prefs/rate_16p0.json "${@:3}"


python3 -m fitting.combine.plot_lim -o $output_dir/lim_prefs_r0.png $in_dir/prefs/lim_0p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_prefs_r1.png $in_dir/prefs/sig_1p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_prefs_r4.png $in_dir/prefs/sig_4p0.json "${@:3}"
python3 -m fitting.combine.plot_sig -o $output_dir/sig_prefs_r16.png $in_dir/prefs/sig_16p0.json "${@:3}"

