#!/usr/bin/env bash


signal_coup=$1
signal_point=$2
cat=$3
area=$4
dir=$5

function printAndRun(){
    echo "$@"
    $@
}

printAndRun python3 -m fitting.cli -l DEBUG estimate -o $dir/signal_${signal_coup}_${signal_point} \
    -n signal_${signal_coup}_${signal_point} \
    -r Signal${signal_coup} \
    -b /srv/backgrounds/background_2025_04_23/Signal${signal_coup}/${area}_${cat}/background_0/background_0.pkl \
    -s /srv/export_hists/signal_${signal_coup}_${signal_point}/Signal${signal_coup}/${cat}_0p67_m14_vs_mChiRatio.pkl \
    "${@:6}"

# printAndRun python3 -m fitting.cli -l DEBUG estimate -o $dir/signal_${signal_coup}_${signal_point} \
#     -n signal_${signal_coup}_${signal_point} \
#     -r Signal${signal_coup} \
#     -b backgrounds/background_2025_04_16/Signal${signal_coup}/${area}_${cat}/background_0/background_0.pkl \
#     -s export_hists/signal_${signal_coup}_${signal_point}/Signal${signal_coup}/${cat}_0p67_m14_vs_mChiRatio.pkl \
#     "${@:6}"


# printAndRun python3 -m fitting.cli -l DEBUG estimate -o $dir/signal_${signal_coup}_${signal_point} \
#     -n signal_${signal_coup}_${signal_point} \
#     -r Signal${signal_coup} \
#     -b backgrounds/control_background_2025_04_23/Control/${area}_${cat}/background.pkl \
#     -s export_hists/signal_${signal_coup}_${signal_point}/Signal${signal_coup}/${cat}_0p67_m14_vs_mChiRatio.pkl \
#     "${@:6}"
