#!/usr/bin/env bash


mode=$1
year=$2
signal_coup=$3
signal_point=$4
cat=$5
area=$6
dir=$7

function printAndRun(){
    echo "$@"
    $@
}
if [[ $cat =~ uncomp ]]; then
    realcat=uncomp 
else
    realcat=comp
fi

echo "${@:7}"
case $mode in
    SR)
        printAndRun python3 -m fitting.cli -l DEBUG estimate -o $dir/$mode/signal_${signal_coup}_${signal_point} \
            -n signal_${signal_coup}_${signal_point} \
            -r Signal${signal_coup} \
            -b /srv/backgrounds/background_2025_06_26_rbf/$year/Signal${signal_coup}/${area}_${cat}/background_0/background_0.pkl \
            -s /srv/export_hists/signal_${signal_coup}_${signal_point}/Signal${signal_coup}/${realcat}_0p67_m14_vs_mChiRatio.pkl \
            "${@:8}"
        ;;
    CR)
        printAndRun python3 -m fitting.cli -l DEBUG estimate -o $dir/$mode/signal_${signal_coup}_${signal_point} \
            -n signal_${signal_coup}_${signal_point} \
            -r Signal${signal_coup} \
            -b backgrounds/background_2025_06_26_rbf/$year/Control/${area}_${cat}/background.pkl \
            -s export_hists/signal_${signal_coup}_${signal_point}/Signal${signal_coup}/${cat}_0p67_m14_vs_mChiRatio.pkl \
            "${@:8}"
        ;;
esac




