#!/usr/bin/env bash	

echo $APPTAINER_COMMAND
source /cvmfs/cms.cern.ch/cmsset_default.sh
pushd $PWD
ls /home
cd /home/cmsusr/CMSSW_14_1_0_pre4
cmsenv  
popd
pwd
base=$1
signal=$2
dest=$(realpath $3)

mkdir -p $dest
(
    cd $base
    find $signal -iname '*.root' | xargs -i cp --parents {} $dest
    find $signal -iname '*.txt'  | xargs -i cp --parents {}  $dest
)

ls -alhtr $dest/$signal/inject_r_1p0/

echo "STARTING COMBINE"


# combineTool.py -M T2W -d $dest/$signal/*/datacard.txt  
combineTool.py -M Significance -d $dest/$signal/inject_r_1p0/datacard.txt  --there -n .sig  -t -1 --expectSignal=1
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_1p0/datacard.txt  --there -n .fit  -t -1 --expectSignal=1

combineTool.py -M Significance -d $dest/$signal/inject_r_4p0/datacard.txt  --there -n .sig  -t -1 --expectSignal=4
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_4p0/datacard.txt  --there -n .fit  -t -1 --expectSignal=4

combineTool.py -M Significance -d $dest/$signal/inject_r_16p0/datacard.txt  --there -n .sig  -t -1  --expectSignal=16
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_16p0/datacard.txt  --there -n .fit  -t -1 --expectSignal=16

combineTool.py -M AsymptoticLimits -d $dest/$signal/inject_r_0p0/datacard.txt  --there -n .lim  -t -1 
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_0p0/datacard.txt  --there -n .fit -t -1


echo "DONE WITH COMBINE"
ls -alhtr $dest/$signal/inject_r_1p0/
