#!/usr/bin/env bash	

echo $APPTAINER_COMMAND
source /cvmfs/cms.cern.ch/cmsset_default.sh
pushd $PWD
ls /home
cd /home/cmsusr/CMSSW_14_1_0_pre4
cmsenv  
popd
pwd
base=$1
signal=$2
dest=$(realpath $3)

mkdir -p $dest
(
    cd $base
    find $signal -iname '*.root' | xargs -i cp --parents {} $dest
    find $signal -iname '*.txt'  | xargs -i cp --parents {}  $dest
)

ls -alhtr $dest/$signal/inject_r_1p0/

echo "STARTING COMBINE"


# combineTool.py -M T2W -d $dest/$signal/*/datacard.txt  
text2workspace.py $dest/$signal/inject_r_0p0/datacard.txt
text2workspace.py $dest/$signal/inject_r_1p0/datacard.txt
text2workspace.py $dest/$signal/inject_r_4p0/datacard.txt
text2workspace.py $dest/$signal/inject_r_9p0/datacard.txt
text2workspace.py $dest/$signal/inject_r_16p0/datacard.txt

combineTool.py -M Significance -d $dest/$signal/inject_r_1p0/datacard.root  --there -n .sig  
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_1p0/datacard.root  --there -n .fit  

combineTool.py -M Significance -d $dest/$signal/inject_r_4p0/datacard.root  --there -n .sig
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_4p0/datacard.root  --there -n .fit

combineTool.py -M Significance -d $dest/$signal/inject_r_9p0/datacard.root  --there -n .sig
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_9p0/datacard.root  --there -n .fit

combineTool.py -M Significance -d $dest/$signal/inject_r_16p0/datacard.root  --there -n .sig 
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_16p0/datacard.root  --there -n .fit 

combineTool.py -M AsymptoticLimits -d $dest/$signal/inject_r_0p0/datacard.root  --there -n .limasimov  -t -1 
combineTool.py -M AsymptoticLimits -d $dest/$signal/inject_r_0p0/datacard.root  --there -n .lim -t -1
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_0p0/datacard.root  --there -n .fitasimov -t -1
combineTool.py -M MultiDimFit -d $dest/$signal/inject_r_0p0/datacard.root  --there -n .fit


echo "DONE WITH COMBINE"
ls -alhtr $dest/$signal/inject_r_1p0/
