#!/usr/bin/env bash	

echo $APPTAINER_COMMAND
source /cvmfs/cms.cern.ch/cmsset_default.sh
pushd $PWD
ls /home
cd /home/cmsusr/CMSSW_14_1_0_pre4
cmsenv  
popd
pwd
base=$1
signal=$2



dest=$(realpath $3)

function printAndRun(){
    echo "$@"
    $@
}

mkdir -p $dest
(
    cd $base
    find $signal -iname '*.root' | xargs -i cp --parents {} $dest
    find $signal -iname '*.txt'  | xargs -i cp --parents {}  $dest
    find $signal -iname '*.json'  | xargs -i cp --parents {}  $dest
)

ls -alhtr $dest/$signal/inject_r_1p0/

echo "STARTING COMBINE"

common_opts="--rMin=-5 --rMax=20 --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,Migrad,0:0.1 --cminFallbackAlgo Minuit2,Migrad,1:1.0 --cminFallbackAlgo Minuit2,Migrad,0:1.0 --X-rtd MINIMIZER_MaxCalls=999999999 --X-rtd MINIMIZER_analytic  --X-rtd FAST_VERTICAL_MORPH"

# combineTool.py -M T2W -d $dest/$signal/*/datacard.txt  


for i in {0..15}; do
    function runSignal(){
        local base=$dest/$signal/$i/inject_r_$1p0/
        printAndRun text2workspace.py $base/datacard.txt -o $base/datacard.root
        printAndRun combineTool.py -M Significance -d $base/datacard.root  --there -n .sig $common_opts > $base/sig.log
        printAndRun combineTool.py -M MultiDimFit -d $base/datacard.root  --there -n .fit  $common_opts  > $base/fit.log
    }

    function runNoInject(){
        local base=$dest/$signal/$i/inject_r_0p0/
        printAndRun text2workspace.py $base/datacard.txt -o $base/datacard.root
        printAndRun combineTool.py -M AsymptoticLimits -d $base/datacard.root  --there -n .limasimov  -t -1   $common_opts > $base/limasimov.log
        printAndRun combineTool.py -M AsymptoticLimits -d $base/datacard.root  --there -n .lim -t -1 $common_opts > $base/lim.log
        printAndRun combineTool.py -M MultiDimFit -d      $base/datacard.root  --there -n .fit  $common_opts > $base/fit.log
        # combineTool.py -M GoodnessOfFit -d $dest/$signal/inject_r_0p0/datacard.root  --there -n .gof_toys --algo KS -t 500 --rMin=-5 --rMax=20
        # combineTool.py -M GoodnessOfFit -d $dest/$signal/inject_r_0p0/datacard.root  --there -n .gof_obs --algo KS  --rMin=-5 --rMax=20
        # combineTool.py -M CollectGoodnessOfFit --input *.gof_toys* *.gof_obs* -m 125.0 -o gof.json 
    }

    runSignal 1
    runSignal 4
    runSignal 9
    runSignal 16
    runNoInject


    echo "DONE WITH COMBINE"
    ls -alhtr $dest/$signal/$i/inject_r_1p0/

done
