#!/usr/bin/env bash	

(
    tar xzf temp/env.tar.gz
    source setup.sh bashrc
    shopt -s globstar
    ls -alhtr

    python3 -m fitting.cli estimate "$@"
    python3 -m fitting.cli make-datacard --base $OUTDIR --output $OUTDIR $OUTDIR/**/bkg_estimation_result.pth 
)

echo "Running combine in $(find $OUTDIR -iname '*inject*' -type d)"

apptainer exec -B /cvmfs -B /eos -B /afs /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/combine-container:latest /bin/bash distributed/combine_script_inline $(find $OUTDIR -iname '*inject*' -type d)

