#!/usr/bin/env bash	

tar xzf temp/env.tar.gz
source setup.sh bashrc
shopt -s globstar
ls -alhtr

coupling=$1
year=$2
input=$3
name=$4
dataset=$5
cat=$6
x_low=$7
x_high=$8
y_low=$9
y_high=${10}
rebin=${11}

python3 -m fitting.cli bkg-smooth -n $dataset -o $OUTDIR/$year/$coupling/${name}_${cat} -s $coupling \
    -i $input \
    -x $x_low,$x_high -y $y_low,$y_high  --rebin $rebin  #$extras ${@:4}

    #-i export_hists/$dataset/$coupling/${cat}_0p67_m14_vs_mChiRatio.pkl \
